name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Vite Github Pages Deployer
      uses: skywarth/vite-github-pages-deployer@v1.5.0
      id: deploy_to_pages
      with:
        build_path: ./dist
        install_phase_node_env: dev
        build_phase_node_env: production
        package_manager: pnpm
        artifact_name: github-pages
        debug_mode: false
        working_path: ./
